#!/usr/bin/env bash
# =============================================
# Echoo: local development with ngrok tunnels
# =============================================
# Starts the backend, the frontend (Vite), and two ngrok tunnels
# (backend -> 5001, frontend -> 5174) using a unified config file.
#
# Usage (from repo root):
#   ./scripts/dev-ngrok.sh [YOUR_NGROK_AUTHTOKEN]
# =============================================
set -u

# Capture token from argument if provided
TOKEN="${1:-}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
PID_DIR="$ROOT_DIR/.dev-ngrok"
FRONTEND_ENV="$FRONTEND_DIR/.env"
NGROK_CONFIG="$PID_DIR/ngrok.yml"

cleanup() {
  echo
  echo "[dev-ngrok] Shutting down..."
  if [ -d "$PID_DIR" ]; then
    for pidfile in "$PID_DIR"/*.pid; do
      [ -f "$pidfile" ] || continue
      pid=$(cat "$pidfile" 2>/dev/null)
      [ -n "$pid" ] && kill "$pid" 2>/dev/null
    done
    rm -rf "$PID_DIR"
  fi
  kill 0 2>/dev/null
  exit 0
}
trap cleanup INT TERM

mkdir -p "$PID_DIR"

# --------------------------------------------------
# Backend & Frontend
# --------------------------------------------------
echo "[dev-ngrok] Starting Echoo backend on :5001 ..."
( cd "$BACKEND_DIR" && exec npm run dev ) > "$PID_DIR/backend.log" 2>&1 &
echo $! > "$PID_DIR/backend.pid"

echo "[dev-ngrok] Starting Echoo frontend on :5174 ..."
( cd "$FRONTEND_DIR" && exec npm run dev ) > "$PID_DIR/frontend.log" 2>&1 &
echo $! > "$PID_DIR/frontend.pid"

# --------------------------------------------------
# LiveKit Cloud preflight
# --------------------------------------------------
if [ -f "$BACKEND_DIR/.env" ] && grep -q "^LIVEKIT_URL=" "$BACKEND_DIR/.env"; then
  LIVEKIT_CFG=$(grep "^LIVEKIT_URL=" "$BACKEND_DIR/.env" | head -1 | cut -d= -f2-)
  if printf '%s' "$LIVEKIT_CFG" | grep -qE "^wss://"; then
    echo "[dev-ngrok] LiveKit Cloud detected: $LIVEKIT_CFG"
  else
    echo "[dev-ngrok] WARNING: LiveKit is not configured for public use."
  fi
else
  echo "[dev-ngrok] WARNING: no backend/.env or LIVEKIT_URL not set."
fi

# --------------------------------------------------
# ngrok tunnels (using config file)
# --------------------------------------------------
echo "[dev-ngrok] Starting ngrok tunnels..."

# If token provided, add it to the config file directly
cat > "$NGROK_CONFIG" <<EOF
version: "2"
$( [ -n "$TOKEN" ] && echo "authtoken: $TOKEN" )
tunnels:
  echoo-backend:
    proto: http
    addr: 5001
  echoo-frontend:
    proto: http
    addr: 5174
EOF

# Use the user's default config if it exists, otherwise rely on NGROK_AUTHTOKEN env var
USER_CONFIG_PATH=$(ngrok config check 2>&1 | grep "stat " | awk '{print $2}' | tr -d ':' | head -1)
[ -z "$USER_CONFIG_PATH" ] && USER_CONFIG_PATH="$HOME/.config/ngrok/ngrok.yml"

NGROK_CMD="ngrok start --all --config $NGROK_CONFIG"
# Only merge with user config if we don't have a direct token in our custom config
if [ -z "$TOKEN" ] && [ -f "$USER_CONFIG_PATH" ]; then
    NGROK_CMD="ngrok start --all --config $USER_CONFIG_PATH --config $NGROK_CONFIG"
fi

( exec $NGROK_CMD ) > "$PID_DIR/ngrok.log" 2>&1 &
echo $! > "$PID_DIR/ngrok.pid"

# --------------------------------------------------
# Capture URLs via ngrok local API
# --------------------------------------------------
BACKEND_URL=""
FRONTEND_URL=""

echo -n "[dev-ngrok] Waiting for tunnels to come online..."
for i in {1..20}; do
  echo -n "."
  sleep 1
  tunnels=$(curl -s http://127.0.0.1:4040/api/tunnels)
  if [ -n "$tunnels" ]; then
    BACKEND_URL=$(echo "$tunnels" | grep -oE 'https://[A-Za-z0-9.-]+\.ngrok-free\.(dev|app)' | grep -v '5174' | head -1 || true)
    # The frontend is the one forwarding to 5174
    FRONTEND_URL=$(echo "$tunnels" | python3 -c "import sys, json; data=json.load(sys.stdin); print(next((t['public_url'] for t in data['tunnels'] if '5174' in t['config']['addr']), ''))" 2>/dev/null || true)
    
    # If python fails, try a simple grep fallback
    if [ -z "$FRONTEND_URL" ]; then
        FRONTEND_URL=$(echo "$tunnels" | grep -oE 'https://[A-Za-z0-9.-]+\.ngrok-free\.(dev|app)' | head -2 | tail -1)
    fi

    if [ -n "$BACKEND_URL" ] && [ -n "$FRONTEND_URL" ]; then
      echo " OK"
      break
    fi
  fi
done

if [ -z "$BACKEND_URL" ] || [ -z "$FRONTEND_URL" ]; then
  echo
  echo "[dev-ngrok] ERROR: could not detect ngrok URLs."
  echo "[dev-ngrok] Make sure ngrok is authenticated: ngrok config check"
  cat "$PID_DIR/ngrok.log"
else
  echo
  echo "[dev-ngrok] ============================================="
  echo "[dev-ngrok] Backend API:    $BACKEND_URL/api/health"
  echo "[dev-ngrok] Frontend app:   $FRONTEND_URL"
  echo "[dev-ngrok] ============================================="

  # Preserve existing VITE_LIVEKIT_URL
  EXISTING_LK=""
  [ -f "$FRONTEND_ENV" ] && EXISTING_LK=$(grep "^VITE_LIVEKIT_URL=" "$FRONTEND_ENV" | head -1 | cut -d= -f2-)

  cat > "$FRONTEND_ENV" <<EOF
# AUTO-GENERATED by scripts/dev-ngrok.sh
VITE_API_URL=$BACKEND_URL/api
VITE_LIVEKIT_URL=$EXISTING_LK
VITE_SYNTHETIC_AUDIO=false
EOF
  echo "[dev-ngrok] Updated $FRONTEND_ENV"
  echo "[dev-ngrok] NOTE: Vite needs a restart to pick up the new .env."
  echo "[dev-ngrok]       Run: cd frontend && (kill \$(cat $PID_DIR/frontend.pid); npm run dev) &"
fi

echo "[dev-ngrok] Press Ctrl+C to stop all services."
wait
