#!/usr/bin/env bash
# =============================================
# Echoo: hosting through GitHub Codespaces
# =============================================
# Starts the backend and frontend in a Codespace.
# Automatically detects the Codespace URL and configures the frontend.
#
# Usage:
#   ./scripts/dev-codespaces.sh
# =============================================
set -u

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
PID_DIR="$ROOT_DIR/.dev-codespaces"
FRONTEND_ENV="$FRONTEND_DIR/.env"

cleanup() {
  echo
  echo "[dev-codespaces] Shutting down..."
  [ -d "$PID_DIR" ] && rm -rf "$PID_DIR"
  kill 0 2>/dev/null
  exit 0
}
trap cleanup INT TERM

mkdir -p "$PID_DIR"

# --------------------------------------------------
# Codespace URL Detection
# --------------------------------------------------
if [ -z "${CODESPACE_NAME:-}" ]; then
  echo "[dev-codespaces] ERROR: Not running in a GitHub Codespace."
  exit 1
fi

# Codespaces uses a specific URL pattern for forwarded ports
# Format: https://<codespace-name>-<port>.app.github.dev
APP_URL="https://${CODESPACE_NAME}-5173.app.github.dev"
API_URL="https://${CODESPACE_NAME}-5173.app.github.dev/api"

echo "[dev-codespaces] Codespace detected: ${CODESPACE_NAME}"
echo "[dev-codespaces] Expected App URL: $APP_URL"

# --------------------------------------------------
# Environment Setup
# --------------------------------------------------
# Preserve existing VITE_LIVEKIT_URL
EXISTING_LK=""
[ -f "$FRONTEND_ENV" ] && EXISTING_LK=$(grep "^VITE_LIVEKIT_URL=" "$FRONTEND_ENV" | head -1 | cut -d= -f2-)

cat > "$FRONTEND_ENV" <<EOF
# AUTO-GENERATED by scripts/dev-codespaces.sh
VITE_API_URL=$API_URL
VITE_LIVEKIT_URL=$EXISTING_LK
VITE_SYNTHETIC_AUDIO=false
EOF
echo "[dev-codespaces] Updated $FRONTEND_ENV"

# --------------------------------------------------
# Start Services
# --------------------------------------------------
echo "[dev-codespaces] Starting Echoo backend on :5001 ..."
( cd "$BACKEND_DIR" && exec npm run dev ) &

echo "[dev-codespaces] Starting Echoo frontend on :5173 ..."
( cd "$FRONTEND_DIR" && exec npm run dev ) &

echo
echo "[dev-codespaces] ============================================="
echo "[dev-codespaces] 1. Go to the 'PORTS' tab in VS Code."
echo "[dev-codespaces] 2. Right-click port 5173 and set 'Port Visibility' to PUBLIC."
echo "[dev-codespaces] 3. Open this link: $APP_URL"
echo "[dev-codespaces] ============================================="
echo
echo "[dev-codespaces] Press Ctrl+C to stop all services."
wait
