#!/usr/bin/env bash
# =============================================
# Echoo: local development with a single ngrok tunnel
# =============================================
# Starts the backend and frontend, then opens ONE tunnel to the
# frontend (port 5173). API requests are proxied automatically.
#
# Usage (from repo root):
#   ./scripts/dev-ngrok.sh [YOUR_NGROK_AUTHTOKEN]
# =============================================
set -u

# Capture token from argument if provided
TOKEN="${1:-}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
PID_DIR="$ROOT_DIR/.dev-ngrok"
FRONTEND_ENV="$FRONTEND_DIR/.env"
NGROK_CONFIG="$PID_DIR/ngrok.yml"

cleanup() {
  echo
  echo "[dev-ngrok] Shutting down..."
  if [ -d "$PID_DIR" ]; then
    for pidfile in "$PID_DIR"/*.pid; do
      [ -f "$pidfile" ] || continue
      pid=$(cat "$pidfile" 2>/dev/null)
      [ -n "$pid" ] && kill "$pid" 2>/dev/null
    done
    rm -rf "$PID_DIR"
  fi
  kill 0 2>/dev/null
  exit 0
}
trap cleanup INT TERM

mkdir -p "$PID_DIR"

# --------------------------------------------------
# Backend & Frontend
# --------------------------------------------------
echo "[dev-ngrok] Starting Echoo backend on :5001 ..."
( cd "$BACKEND_DIR" && exec npm run dev ) > "$PID_DIR/backend.log" 2>&1 &
echo $! > "$PID_DIR/backend.pid"

echo "[dev-ngrok] Starting Echoo frontend on :5173 ..."
( cd "$FRONTEND_DIR" && exec npm run dev ) > "$PID_DIR/frontend.log" 2>&1 &
echo $! > "$PID_DIR/frontend.pid"

# --------------------------------------------------
# LiveKit Cloud preflight
# --------------------------------------------------
if [ -f "$BACKEND_DIR/.env" ] && grep -q "^LIVEKIT_URL=" "$BACKEND_DIR/.env"; then
  LIVEKIT_CFG=$(grep "^LIVEKIT_URL=" "$BACKEND_DIR/.env" | head -1 | cut -d= -f2-)
  if printf '%s' "$LIVEKIT_CFG" | grep -qE "^wss://"; then
    echo "[dev-ngrok] LiveKit Cloud detected: $LIVEKIT_CFG"
  else
    echo "[dev-ngrok] WARNING: LiveKit is not configured for public use."
  fi
else
  echo "[dev-ngrok] WARNING: no backend/.env or LIVEKIT_URL not set."
fi

# --------------------------------------------------
# ngrok tunnel (Single Tunnel)
# --------------------------------------------------
echo "[dev-ngrok] Starting ngrok tunnel..."

# If token provided, add it to the config file directly
cat > "$NGROK_CONFIG" <<EOF
version: "2"
$( [ -n "$TOKEN" ] && echo "authtoken: $TOKEN" )
tunnels:
  echoo-app:
    proto: http
    addr: 5173
EOF

( exec ngrok start echoo-app --config "$NGROK_CONFIG" ) > "$PID_DIR/ngrok.log" 2>&1 &
echo $! > "$PID_DIR/ngrok.pid"

# --------------------------------------------------
# Capture URL via ngrok local API
# --------------------------------------------------
APP_URL=""

echo -n "[dev-ngrok] Waiting for tunnel to come online..."
for i in {1..20}; do
  echo -n "."
  sleep 1
  tunnels=$(curl -s http://127.0.0.1:4040/api/tunnels)
  if [ -n "$tunnels" ]; then
    APP_URL=$(echo "$tunnels" | grep -oE 'https://[A-Za-z0-9.-]+\.ngrok-free\.(dev|app)' | head -1 || true)
    if [ -n "$APP_URL" ]; then
      echo " OK"
      break
    fi
  fi
done

if [ -z "$APP_URL" ]; then
  echo
  echo "[dev-ngrok] ERROR: could not detect ngrok URL."
  echo "[dev-ngrok] Make sure ngrok is authenticated."
  cat "$PID_DIR/ngrok.log"
else
  echo
  echo "[dev-ngrok] ============================================="
  echo "[dev-ngrok] YOUR LIVE SITE:  $APP_URL"
  echo "[dev-ngrok] ============================================="

  # Preserve existing VITE_LIVEKIT_URL
  EXISTING_LK=""
  [ -f "$FRONTEND_ENV" ] && EXISTING_LK=$(grep "^VITE_LIVEKIT_URL=" "$FRONTEND_ENV" | head -1 | cut -d= -f2-)

  # In single-tunnel mode, the API is reachable at /api on the SAME URL
  cat > "$FRONTEND_ENV" <<EOF
# AUTO-GENERATED by scripts/dev-ngrok.sh
VITE_API_URL=$APP_URL/api
VITE_LIVEKIT_URL=$EXISTING_LK
VITE_SYNTHETIC_AUDIO=false
EOF
  echo "[dev-ngrok] Updated $FRONTEND_ENV"
  echo "[dev-ngrok] NOTE: Vite needs a restart to pick up the new .env."
  echo "[dev-ngrok]       Run: cd frontend && (kill \$(cat $PID_DIR/frontend.pid); npm run dev) &"
fi

echo "[dev-ngrok] Press Ctrl+C to stop all services."
wait
